<?php

$datas = array(
	"Agriculture, Forestry, Fishing and Hunting",
	"Animal Production",
	"Apiculture",
	"Forestry and Logging",
	"Fishing, Hunting and Trapping",
	"Support Activities for Agriculture and Forestry",
	"Support Activities for Animal Production",
	"Mining",
	"Mining (except Oil and Gas)",
	"Support Activities for Mining",
	"Utilities",
	"Construction",
	"Specialty Trade Contractors",
	"Manufacturing",
	"Textile Mills",
	"Textile Product Mills",
	"Apparel Manufacturing",
	"Leather and Allied Product Manufacturing",
	"Wood Product Manufacturing",
	"Paper Manufacturing",
	"Printing and Related Support Activities",
	"Petroleum and Coal Products Manufacturing",
	"Chemical Manufacturing",
	"Plastics and Rubber Products Manufacturing",
	"Nonmetallic Mineral Product Manufacturing",
	"Primary Metal Manufacturing",
	"Fabricated Metal Product Manufacturing",
	"Machinery Manufacturing",
	"Computer and Electronic Product Manufacturing",
	"Electrical Equipment, Appliance, and Component Manufacturing",
	"Transportation Equipment Manufacturing",
	"Furniture and Related Product Manufacturing",
	"Miscellaneous Manufacturing",
	"Wholesale Trade",
	"Merchant Wholesalers, Nondurable Goods",
	"Wholesale Electronic Markets and Agents and Brokers",
	"Motor Vehicle and Parts Dealers",
	"Furniture and Home Furnishings Stores",
	"Electronics and Appliance Stores",
	"Building Material and Garden Equipment and Supplies Dealers",
	"Food and Beverage Stores",
	"Health and Personal Care Stores",
	"Gasoline Stations",
	"Clothing and Clothing Accessories Stores",
	"Sporting Goods, Hobby, Book, and Music Stores",
	"General Merchandise Stores",
	"Miscellaneous Store Retailers",
	"Nonstore Retailers",
	"Transportation and Warehousing",
	"Postal Service",
	"Warehousing and Storage",
	"Information",
	"Motion Picture and Sound Recording Industries",
	"Broadcasting (except Internet)",
	"Internet Publishing and Broadcasting",
	"Telecommunications",
	"Internet Service Providers, Web Search Portals, and Data Processing Services",
	"Other Information Services",
	"Finance and Insurance",
	"Securities, Commodity Contracts, and Other Financial Investments and Related Activities",
	"Insurance Carriers and Related Activities",
	"Funds, Trusts, and Other Financial Vehicles",
	"Real Estate and Rental and Leasing",
	"Rental and Leasing Services",
	"Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)",
	"Professional, Scientific, and Technical Services",
	"Management of Companies and Enterprises",
	"Administrative and Support and Waste Management and Remediation Services",
	"Waste Management and Remediation Services",
	"Educational Services",
	"Health Care and Social Assistance",
	"Hospitals",
	"Social Assistance",
	"Arts, Entertainment, and Recreation",
	"Amusement, Gambling, and Recreation Industries",
	"Accommodation and Food Services",
	"Other Services (except Public Administration)",
	"Religious, Grantmaking, Civic, Professional, and Similar Organizations",
	"Private Households",
	"Public Administration",
	"Justice, Public Order, and Safety Activities",
	"Administration of Human Resource Programs",
	"Administration of Environmental Quality Programs",
	"Administration of Housing Programs, Urban Planning, and Community Development",
	"Administration of Economic Programs",
	"Space Research and Technology",
	"National Security and International Affairs",
	"OTHER"
);